language: cpp

packages:
  - gcc-5
  - g++-5
  - libstdc++6
  - binutils-gold
  - cmake

#cache:
#  directories:
#  - cmake

#before_install:
#  - dlib/travis/before-install.sh

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ../dlib/dlib/test
  - cmake --build . --target dtest


notifications:
  email:
    false
