language: cpp

packages: &gcc5_pkgs
  - gcc-5
  - g++-5
  - libstdc++6
#  - binutils-gold
#  - cmake

matrix:
  include:
    # GCC/Coverage/Autobahn
    - compiler: gcc
      env:
        - GCC_VER=5
        - ADDRESS_MODEL=64
        - BUILD_SYSTEM=cmake
        - PATH=$PWD/cmake/bin:$PATH
      addons: &ao_gcc5
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages: *gcc5_pkgs
          
cache:
  directories:
  - cmake

before_install:
  - dlib/travis/before-install.sh

script:
  - gcc --version
  - mkdir build
  - cd build
  - cmake --version
  - cmake ../dlib/test
  - cmake --build . --target dtest


notifications:
  email:
    false
