language: cpp

packages:
  - gcc-5
  - g++-5
  - libstdc++6
  - binutils-gold
  - cmake

#cache:
#  directories:
#  - cmake

#before_install:
#  - dlib/travis/before-install.sh

script:
  - dlib/travis/build_and_test.sh

notifications:
  email:
    false
