language: cpp

env:
  global:
    - LLVM_VERSION=3.8.0
    - LCOV_ROOT=$HOME/lcov
    - VALGRIND_ROOT=$HOME/valgrind-install
packages: &gcc5_pkgs
  - gcc-5
  - g++-5
  - libstdc++6
  - binutils-gold
  - cmake
  # Provides a backtrace if the unittests crash
  - gdb
  # Needed for installing valgrind
  - subversion
  - automake
  - autotools-dev
  - libc6-dbg

matrix:
  include:
    # GCC/Coverage/Autobahn
    - compiler: gcc
      env:
        - GCC_VER=5
        - VARIANT=coverage
        - ADDRESS_MODEL=64
        - BUILD_SYSTEM=cmake
        - PATH=$PWD/cmake/bin:$PATH
      addons: &ao_gcc5
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: *gcc5_pkgs

    # Clang/UndefinedBehaviourSanitizer
    - compiler: clang
      env:
        - GCC_VER=5
        - VARIANT=usan
        - CLANG_VER=3.8
        - ADDRESS_MODEL=64
        - UBSAN_OPTIONS='print_stacktrace=1'
        - BUILD_SYSTEM=cmake
        - PATH=$PWD/cmake/bin:$PATH
        - PATH=$PWD/llvm-$LLVM_VERSION/bin:$PATH
      addons: *ao_gcc5

    # Clang/AddressSanitizer
    - compiler: clang
      env:
        - GCC_VER=5
        - VARIANT=asan
        - CLANG_VER=3.8
        - ADDRESS_MODEL=64
        - PATH=$PWD/llvm-$LLVM_VERSION/bin:$PATH
      addons: *ao_gcc5

cache:
  directories:
  - $VALGRIND_ROOT
  - llvm-$LLVM_VERSION
  - cmake

#before_install:
#  - dlib/travis/before_install.sh

script:
  - dlib/travis/build-and-test.sh

notifications:
  email:
    false
