language: cpp

env:
  global:
    - LLVM_VERSION=3.8.0
    - LCOV_ROOT=$HOME/lcov
    - VALGRIND_ROOT=$HOME/valgrind-install
packages: &gcc5_pkgs
  - gcc-5
  - g++-5
  - libstdc++6
  - binutils-gold
  - cmake
  # Provides a backtrace if the unittests crash
  - gdb
  # Needed for installing valgrind
  - subversion
  - automake
  - autotools-dev
  - libc6-dbg

#cache:
#  directories:
#  - cmake

#before_install:
#  - dlib/travis/before-install.sh

script:
  mkdir build
  cd build
  cmake --version
  cmake ../dlib/dlib/test
  cmake --build . --target dtest
  

notifications:
  email:
    false
