language: cpp

packages: &gcc5_pkgs
  - gcc-5
  - g++-5
  - libstdc++6
#  - binutils-gold
#  - cmake

matrix:
  include:
    # GCC/Coverage/Autobahn
      compiler: gcc
      env:
        - GCC_VER=5
        - ADDRESS_MODEL=64
        - BUILD_SYSTEM=cmake
        - PATH=$HOME/bin:/usr/bin:$PATH
        #- CMAKE_ROOT=$PWD/cmake/share/cmake-3.5
      addons: &ao_gcc5
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages: *gcc5_pkgs
          
cache:
  directories:
  - cmake

before_install:
  - dlib/travis/before-install.sh

script:
  - dlib/travis/build-and-test.sh


notifications:
  email:
    false
